
server:  port: 8888
  
spring:  profiles:    active: native #vai buscar as config dentro do file system
  cloud:    config:      server:        native:          search-locations: c:/microservice-repo #as config estão nesta pasta